version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      okta-org-url: https://your-org.okta.com
      okta-api-token: your_api_token_here
      cache-ttl-seconds: 600
      cache-type: memory
    restart: unless-stopped
