BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[admins] (
    [id] UNIQUEIDENTIFIER NOT NULL,
    [email] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [admins_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    [created_by] NVARCHAR(1000),
    CONSTRAINT [admins_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [admins_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH

